### ISSUE TITLE
Android prompt

### ISSUE THREAD

**Issue by SevBob** [kinetic-fit/fit-android-issues#1]
When you try to hit the back arrow to access your profile menu it asks if you want to cancel the workout, then the prompt box offers Cancel or OK.  Should probably change the prompt to "do you want to end your workout" to avoid confusion instead of cancel being used twice.

**Comment by lexicalninja** [comment]
Fixed with commit #1cb27685c in android fit project.
Prompts now say "Are you sure you want to end this workout?"
Will appear in version 2.0.3
