### ISSUE TITLE
Imperial Setting Not Saving After Restart

### ISSUE THREAD

**Issue by jterry7554** [kinetic-fit/fit-android-issues#10]
Upon each startup of the app, the units setting in my profile reverts to Metric.  Have to manually switch to Imperial each time.  Using Google Pixel 3.

**Comment by jterry7554** [comment]
Additional info for above issue

**Smartphone (please complete the following information):**
Pixel 3
Android 10
Version 2.1.2

**Trainer (please complete the following information):**
Road Machine Smart 2
Firmware Unknown

**Comment by lexicalninja** [comment]
The last update added some logic to make sure that the units of measure migrated and may have caused an issue. 

This should not be a major change to make and I will update this once I can locate the issue.

**Comment by lexicalninja** [comment]
Found the bug and patched it. Building and pushing version 2.1.3 (222) for release to alpha. This should fix this bug. If it does not, please reopen this ticket. Thanks.

P
