### ISSUE TITLE
Workout Data

### ISSUE THREAD

**Issue by jterry7554** [kinetic-fit/fit-android-issues#12]
Since switching to Kinetic Fit beta, recent workouts do not show up when signing in to my account in a web browser (only workouts previous to beta update are visible).  Additionally, past workouts (performed in non-beta) do not show up in the beta app.  Would be good to see all workouts in the same place.

**Smartphone (please complete the following information):**
Pixel 3
Android 10
Version 2.1.2

**Trainer (please complete the following information):**
Road Machine Smart 2
Firmware Unknown

**Comment by lexicalninja** [comment]
Thank you for the report. 

This beta version is on a new back end that does not connect to the current production versions  of the Fit app (either iOS or Android), so you will not see all of your workouts across platforms while running the Android beta.

When you first launched the beta and logged in, there should have been a pop up explaining the migration and indicating some data would not come over immediately and that it might take 48 hours to see the data. 

Currently only the last 100 workouts should be migrating. Please let me know if you do not see any past workouts migrate over.
