### ISSUE TITLE
Database Migration did not work

### ISSUE THREAD

**Issue by nextinflexion** [kinetic-fit/fit-android-issues#14]
**Describe the bug**
I signed into the latest Kinetic Android app on 1/29/20 with my previous Kinetic.fit credentials, performed a single workout, and waited for my previous ride history to migrate over. It's been almost 2 weeks and I still have not seen my previous ride history show up.

**To Reproduce**
1. Sign in and wait for database migration

**Expected behavior**
Previous ride history to migrate to latest Kinetic android app

**Screenshots**
![Screenshot_20200211-125908](https://user-images.githubusercontent.com/60940832/74270314-a26a3780-4cd0-11ea-81fd-8d4f2ff05215.png)

**Smartphone (please complete the following information):**
 - Device: Pixel [1]
 - OS: Android
 - Version: 10 (Build #: QP1A.191005.007.A3)

**Trainer (please complete the following information):**
- Trainer: Kinetic R1
- Firmware Version: 2.40

**Additional context**
N/A

**Comment by lexicalninja** [comment]
thanks @nextinflexion 

I will work on the forced migration that we talked about and hopefully we can make that work.

**Comment by lexicalninja** [comment]
@nextinflexion I did some work on migrations yesterday. Can you check and see if it came through?

If not, slack me the email you use to log in and I will see if it was one that needs to be forced.

Thanks

**Comment by nextinflexion** [comment]
Sorry, it did not work. I will DM you on slack.

**Comment by lexicalninja** [comment]
this should be fixed. Any users that experience an issue with migration should open or join an open migration Issue.
