### ISSUE TITLE
T-6200 not connecting to Android Redmi phone

### ISSUE THREAD

**Issue by Sergi0ss** [kinetic-fit/fit-android-issues#15]
I know this is a quite normal issue but can't get to solve it.
I've tried all the tips I found and still can't get to connect my smart control to the phone. It does connect for a few seconds but then it disconnects again. I made sure Bluetooth is not showing the trainer and I've tried different timings when connecting, first opening the app then plug the trainer and viceversa.

To reproduce just try to pair the trainer. It will connect for a few seconds. During this time the firmware update is not posible and then disconnects again.

This happens on my:

Redmi note 8T
Android 9 PKQ1/MIUI Global 11.0.3

Combined with:

T-6200 Smart trainer unit
Serial number: 0000000310-RRSC

**Comment by lexicalninja** [comment]
@Sergi0ss Thank you for the report.

Can you please indicate what version of fit you are using?

**Comment by Sergi0ss** [comment]
Hi,

It's the 1.4.23 (220) versión.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by lexicalninja** [comment]
@Sergi0ss 
Thank you.

This issues page is for the current beta version of fit. That would be any of the 2.x.x versions. 

If you would like to join the beta version and see if the changes that have been made in beta work, please go to the main repository page and follow the instructions in the README to get signed up and start testing. If you are still experiencing this issue on the beta, please come back and let me know on this issue and I will reopen it.

If you prefer to stay on the current production version that you are on, please open a ticket through the [support page](https://support.kurtkinetic.com/hc/en-us) and someone can look into the issue through regular support channels.

**Comment by Sergi0ss** [comment]
Ok, apologies.

I've just signed up. Guess I'll get the download link on my mail right?

**Comment by lexicalninja** [comment]
@Sergi0ss 
When you say signed up, did you follow the instructions on the main page here? You should have opted in on a google page, which then would have given you directions on how to get the beta version from the play store. Was that not the process you went through?

**Comment by Sergi0ss** [comment]
It took me to the Google Page, then I press the "become a tester" buttom but It doesn't do anything.

Maybe a problem with my browser?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by lexicalninja** [comment]
You should have seen a screen like this afterward:
![image](https://user-images.githubusercontent.com/7376126/74883092-d7603500-5335-11ea-9121-43fa87c6e7b3.png)

**Comment by Sergi0ss** [comment]
I see. The web loads the page again and again after pressing the buttom.

Is there a way to find the beta version on Google Play without  clicking on that link? Can I find It by the name?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by lexicalninja** [comment]
Once you join, it says it can take a few hours to join. Once it comes through, you should get an update for kinetic fit. Do you have automatic updates turned on?

**Comment by Sergi0ss** [comment]
Yes, but could It be because I'm logged in to the fit app on a not Gmail account?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by lexicalninja** [comment]
Nope. It just takes time. Sometimes the play store on the phone doesn't update right away. As long as your Gmail that was in the browser is the one the play store is connected to. It doesn't matter what email you use to log into kinetic

**Comment by Sergi0ss** [comment]
Ok, let's wait then. Thank you

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
