### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by mcheppy** [kinetic-fit/fit-android-issues#18]
during my last two workouts, today 3/6 and on 3/4. the app crashes at the end of the workout, before getting to click to results. closing the app and restarting, the app crashes when trying to open the workout to download. th 3/4 ride I was finally able to get downloaded but the 3/6 I have not been able to. 

using pixel 3 running Android 10

**Comment by lexicalninja** [comment]
Sorry for the late response. Can you tell me if you experienced more issues with this or if it is just the one workout?

Can you see the analysis screen for the 3/6 workout or does it crash when you go into it?

**Comment by mcheppy** [comment]
carshes for workouts in 3/6, 3/4, and today 3/17. two rides between 3/4 and 3/17 work fine.  the app crashes before results screen opens, and also when trying to open the results screen afterwards. the app will sometimes not show any rides at all but when restarted they will show up.

**Comment by lexicalninja** [comment]
Do you have auto upload to strava on by any chance?

**Comment by mcheppy** [comment]
Yes I do but can turn that off

**Comment by mcheppy** [comment]
Just unchecked Strava auto. Now can open ride.

**Comment by lexicalninja** [comment]
ok. I can look into what is causing that. see if you can upload it to strava manually from the analysis screen when you have a chance
