### ISSUE TITLE
App crash on Onenote 7 OS10.03version

### ISSUE THREAD

**Issue by Lucylea** [kinetic-fit/fit-android-issues#20]
**Describe the bug**
I did two workout in one day, I can only click to see and share the last one workout data. When I click to the first workout, the app crashed

**To Reproduce**
1. I have done two workout one by one on the same day (see screenshot 1)
2. I can see the detail of first workout at first
3. when I finish the second workout, I can only see the last work out
4. when I click to see the first workout, it return to the first page (see screenshot 2)

**Expected behavior**
I can view my first workout data on the app, I need to share the data with a TrainingPeak

**Screenshots**
![image](https://user-images.githubusercontent.com/45616004/77770150-c5ce2380-707f-11ea-8722-6414f98f51d3.png)
![image](https://user-images.githubusercontent.com/45616004/77770127-bd75e880-707f-11ea-8871-0f96f1d8d486.png)

**Smartphone (please complete the following information):**
 - Oneplus 7
 - Oxygen OS 10.3.1
 - Kinetic Fit Version [e.g. 2.4.1]

**Trainer (please complete the following information):**
- Trainer: Road machine 2
- Sensor black one 

**Additional context**
no

**Comment by Lucylea** [comment]
Describe the bug
Today I select the workout BG HG Tempo 3*15 as training, and it suddently broken down when the training is in progress.

To Reproduce
Steps to reproduce the behavior:
1. I select a workout named BG HG Tempo 3*15
2. After warming up, the workout began, 
3. At about 23mins, the training suddently exit to a page (see screenshot)
4. There's no result left. 

Expected behavior
I can finish the BG HG Tempo 3*15 with result displayed, so I can export the data to training peak

screenshot
![微信图片_20200329142029](https://user-images.githubusercontent.com/45616004/77842784-0be2ce80-71c9-11ea-8c37-b8b124724916.jpg)
Smartphone (please complete the following information):

Oneplus 7
Oxygen OS 10.3.1
Kinetic Fit Version [e.g. 2.4.1]
Trainer (please complete the following information):

Trainer: Road machine 2
Sensor black one
Additional context
no

**Comment by lexicalninja** [comment]
Please only discuss one problem per issue. This way we can clear up each issue as it presents itself and any questions or comments we have can be about a single issue. This will help make solving your issues faster and reduce any confusion about what issue is being talked about on what thread.

Can you please update to the newest version (2.5.1 - 232) and let me know if this is still an issue?

For your second issue, I will be opening a new Issue to see if there is anything we can do. You can find that here #23 

For all issues, you need to include the sensor version, is inRide3 and the firmware version that it is currently on so that I can understand what hardware and firmware you are currently using. 

This information can be found in the sensor setting screen.

**Comment by lexicalninja** [comment]
Also, please put the android version of your OS, not the device launcher version. You should be able to find this in settings.

**Comment by Lucylea** [comment]
android version 10
sensor: inRider, the old black one.
firmware:  I don't know where it is
Actually, I tried the method mentioned in the website below
https://support.kurtkinetic.com/hc/en-us/articles/360018647992-Before-you-ride-Pair-your-trainer-and-update-firmware
but I can't repeat as the video does. When I connect my inRide sensor and click the GEAR icon, it show as screenshot. There's no firmware icon at all. 
![微信图片_20200331201046](https://user-images.githubusercontent.com/45616004/78025058-f5d13b80-738b-11ea-8001-edc9f64ae4d5.jpg)
please advise.

**Comment by lexicalninja** [comment]
OK, It appears that you are using an inRide2 pod. The Trainer Fluid Level control only works for the Smart Control units. It does not change anything in your pod. It simulates a grade between 0 and 9 percent in the magnetic resistance units like Smart Control 1 and 2 and the R1 wheel-off traininer.

This is done in the workout on android by using the volume up and down buttons. You can see the current setting by adding the Slope icon under the power options in the Custom Displays.

But, as I said, if you are not on a Smart Trainer and are only using the Road Machine with inRide pod, it will not do anything for your machine.

**Comment by lexicalninja** [comment]
@Lucylea thank you. You have an inRide2. I will add some data to this screen today to pull all the information that is normally supposed to be there since we updated our protocals.

Are you still having the issue with the workout not opening in the new version of the app?

**Comment by Lucylea** [comment]
@lexicalninja thank you, I don't have the not opening workout in the new version problem, and the previously not opening workout could also be opened in the new version.

**Comment by Lucylea** [comment]
Yes, I only using the Road Machine with inRide pod, maybe in the future, I will try the smart control unit.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lexicalninja"<notifications@github.com&gt;; 
发送时间: 2020年4月1日(星期三) 凌晨2:28
收件人: "kinetic-fit/fit-android-issues"<fit-android-issues@noreply.github.com&gt;; 
抄送: "ーぅ壞ヤo"<497717576@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kinetic-fit/fit-android-issues] App crash on Onenote 7 OS10.03version (#20)





 
OK, It appears that you are using an inRide2 pod. The Trainer Fluid Level control only works for the Smart Control units. It does not change anything in your pod. It simulates a grade between 0 and 9 percent in the magnetic resistance units like Smart Control 1 and 2 and the R1 wheel-off traininer.
 
This is done in the workout on android by using the volume up and down buttons. You can see the current setting by adding the Slope icon under the power options in the Custom Displays.
 
But, as I said, if you are not on a Smart Trainer and are only using the Road Machine with inRide pod, it will not do anything for your machine.
