### ISSUE TITLE
Can't favorite and dis-favorite a workout

### ISSUE THREAD

**Issue by Lucylea** [kinetic-fit/fit-android-issues#22]
**Describe the bug**
Can't favorite and dis-favorite a workout

**To Reproduce**
1. Go to select workout 
2. Click on any workout, and click the favorite star in left bottom 
3. The star is not turning on
**To Reproduce**
Steps to reproduce the behavior
1. Go to my favorite workout 
2. Click on any workout, and click the favorite star
3. The star in not turning off 

**Expected behavior**
The favorite star turn on and off as I expected

**Screenshots**
Not available

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - oxygen OS 10.3.1
 - Kinetic Fit Version 2.4.1

**Trainer (please complete the following information):**
- Road machine smart 2 
- Black sensor

**Additional context**
No

**Comment by lexicalninja** [comment]
I have fixed this bug. It should go out with the next version that is pushed. You should see this in version 2.5.2 (233) when it is released in the next 24 hours
