### ISSUE TITLE
Workout crashed mid workout.

### ISSUE THREAD

**Issue by lexicalninja** [kinetic-fit/fit-android-issues#23]
Describe the bug
Today I select the workout BG HG Tempo 3*15 as training, and it suddently broken down when the training is in progress.

To Reproduce
1. I select a workout named BG HG Tempo 3*15
2. After warming up, the workout began, 
3. At about 23mins, the training suddently exit to a page (see screenshot)
4. There's no result left. 

Expected behavior
I can finish the BG HG Tempo 3*15 with result displayed, so I can export the data to training peak

screenshot
![微信图片_20200329142029](https://user-images.githubusercontent.com/45616004/77842784-0be2ce80-71c9-11ea-8c37-b8b124724916.jpg)
Smartphone (please complete the following information):

Oneplus 7
Oxygen OS 10.3.1
Kinetic Fit Version [e.g. 2.4.1]
Trainer (please complete the following information):

Trainer: Road machine 2
Sensor black one
Additional context
no

_Originally posted by @Lucylea in https://github.com/kinetic-fit/fit-android-issues/issues/20#issuecomment-605589734_

**Comment by lexicalninja** [comment]
@Lucylea 
Has this issue occurred more than once, or just the one time?

**Comment by Lucylea** [comment]
I have only tried once, and it crashed, maybe I will try it tonight

**Comment by Lucylea** [comment]
The bug also exists in 2.5.1 version&nbsp;
I tried the same workout tonight, and it seems to crash at the same position, that is in 14 minutes, where the second cool down end and the second interval begins.&nbsp;
BG HG Tempo 3*15
 
---Original---

**Comment by Lucylea** [comment]
Smartphone (please complete the following information):

Oneplus 7
Android 10
Kinetic Fit Version 2.5.2
Trainer (please complete the following information):

Trainer: Road machine 2
Sensor inRider, old black one
firmware: version 2.0
Additional context
no

**Comment by lexicalninja** [comment]
@Lucylea I think I may have found something that was causing this, but am not sure. Please update to 2.5.4 (235) when it becomes available and let me know. Thanks.

**Comment by Lucylea** [comment]
Yes, you made it! 
It would crack mid training until I updated to 2.5.4

**Comment by lexicalninja** [comment]
Excellent!! Thank you for your help fixing this.
