### ISSUE TITLE
Stats are incorrect

### ISSUE THREAD

**Issue by jacco411** [kinetic-fit/fit-android-issues#24]
**Describe the bug**
Did the recovery 6x5 without today. Workout was flawless but when I went to look at the stats post-workout, the numbers are all over the place. Very large numbers for everything in the session analysis.

**To Reproduce**
1. Go to recovery workout 6x5.
2. Click on session analysis
3. Scroll down to anywhere on the page

**Expected behavior**
I expected to see 45:21 for session time, about 320kcal and 11+ miles

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s9+
 - OS: Android 10
 - Kinetic Fit Version 2.5.4

**Trainer (please complete the following information):**
- Trainer: rock n roll control
- Firmware Version 1.3

**Additional context**
This only happened after the latest 2.5.4 beta update

**Comment by lexicalninja** [comment]
Can you please export as file and attach it to this issue request so that I can look at the data?

**Comment by jacco411** [comment]
I'm not sure how to attach this file from my phone. It says that the file isn't supported





[Larry Lam-20200405-11246573623772592491887.txt](https://github.com/kinetic-fit/fit-android-issues/files/4445431/Larry.Lam-20200405-11246573623772592491887.txt)

**Comment by lexicalninja** [comment]
can you change the file type from .fit to .txt? if you can do that, I can rename it when I download it

otherwise please email it to patrick@codeinversion.com

**Comment by jacco411** [comment]
I just added it to the previous comment. I can also add it here 
[Larry Lam-20200405-11246573623772592491887.txt](https://github.com/kinetic-fit/fit-android-issues/files/4445433/Larry.Lam-20200405-11246573623772592491887.txt)

**Comment by lexicalninja** [comment]
can you export it as a csv this time? It appears that the data is so strange that my fit file readers dont believe it is a fit file.

**Comment by lexicalninja** [comment]
Wow, I got it to import. There is something very wrong there. Can you send your email address that you use to log in to the one I left above? I will need to copy that data from the database and see what happened. Thanks in advance.

**Comment by jacco411** [comment]
lam.larry8@gmail.com

**Comment by lexicalninja** [comment]
can you send me all of the values in the firmware box in the sensor settings screen?

Something caused the data to get corrupted and I want to check a few things

EDIT:
Please also let me know if this happens again on your next workout. Thanks

**Comment by jacco411** [comment]
Here you go. It's a screenshot
![Screenshot_20200407-154634_Kinetic](https://user-images.githubusercontent.com/62756796/78712724-0d0dad00-78e7-11ea-99fa-5b4da111eb23.jpg)

**Comment by jacco411** [comment]
I did a workout today and the stats displayed correctly. I did cross cross super threshold 1x20

**Comment by jacco411** [comment]
As another update, I've done a couple more workouts and no error. I did the same recover 6x5 and cross cross threshold 1x12

**Comment by lexicalninja** [comment]
ok. It looks like that workout had something happen to it. I can't salvage the data, as the errors are in the hard binary data. If you see this again, let me know and see if you can tell if anything out of the ordinary happened when it was finishing up.
