### ISSUE TITLE
Improve User Experience

### ISSUE THREAD

**Issue by Lucylea** [kinetic-fit/fit-android-issues#25]
**Describe the bug**
I click to see a work out, then I return to the previous GUI, it shows the begining of the workout list rather than where I have looked through

**To Reproduce**
1. Go to ' select workout'
2. Click on ' any of them'
3. return to "select workout GUI"
4. it shows the begining of the list

**Expected behavior**
when I return to the previous GUI, I just want to go back to where I have left and continue to look through the remaining workout. 

**Screenshots**
n.a

**Smartphone (please complete the following information):**
 - Oneplus 7
 - Android OS 10
 - Kinetic Fit Version 2.5.4

**Trainer (please complete the following information):**
n.a

**Additional context**
n.a

**Comment by lexicalninja** [comment]
I will add this as an enhancement request that I will look into once the critical errors start slowing down. Thank you for the idea.

**Comment by lexicalninja** [comment]
this should be fixed in 2.5.5. Let me know if it isn't
