### ISSUE TITLE
R1 won't calibrate stuck on pedal up to 25mph

### ISSUE THREAD

**Issue by cdb27** [kinetic-fit/fit-android-issues#26]
**Describe the bug**
During the calibration process the status does not change to tell you to stop pedalling so calibration cannot be completed.

**To Reproduce**
1. Go to sensors and pair trainer.
2. Do a 10 minute warmup followed by a 10 minute free ride.
3. Go to sensors again, click on the cog.
4. Click calibrate.
5. Pedal up to the required speed then nothing happens.

**Expected behavior**
Once the trainer reaches the required speed I am asked to stop pedalling and coast to a stop to allow for calibration.

Screenshots
![Screenshot_20200409-073021_Kinetic](https://user-images.githubusercontent.com/63427966/78943086-fa47d380-7ab2-11ea-8023-3c973b66f00a.jpg)

 - Device: Samsung S10e
 - OS: Android 10
 - Kinetic Fit Version 2.5.4

- Trainer: Kinetic R1
- Firmware Version 2.40

**Comment by lexicalninja** [comment]
Thank you for the report. Is this a common occurrence or has it happened once?

Please try to restart your phone and unplug the R1 for a minute and then plug it back in. The trainer may be stuck on a command during the calibration. You can test that this process works before you calibrate for real by going to the sensor screen right after you pair and running a cold calibration to see if the trainer succeeds before spending 20 minutes warming the trainer up.

Let me know if this is still occurring after these steps.

As a side note, remember that you only need to calibrate the R1 once and not every day like previous trainers. So if this continues to keep you from calibrating, we will likely need to escalate this to the OEM.

Thanks.

**Comment by cdb27** [comment]
I have now managed to get it to work. I had to grease the freehub then it seemed to pick it up ok. Though it calibrates around 10-11 second which seems very high to me? What would the normal calibration time be?

**Comment by lexicalninja** [comment]
The folks at Kinetic tell me that with the R1, there is a normal range, but being outside of that should not affect your trainer. With the R1, whatever the calibration is should be correct for your machine. If you have any issues with this or you think that your power numbers are off, you can open a support ticket with the app or online at kinetic.fit/support and they can help you get your trainer tuned. 

Thanks.
