### ISSUE TITLE
specific name of workout doesn't show in trainingpeaks

### ISSUE THREAD

**Issue by Lucylea** [kinetic-fit/fit-android-issues#27]
**Describe the bug**
I used to syn my workout in kinetic app to trainingpeaks, the title of the workout is always "Cycling" rather than specific name of a workout

**To Reproduce**
1. Go to 'workout'
2. Click on 'syn to trainingpeaks'
3. the activity title is only "Cycling"

**Expected behavior**
It would be nice if I can see which workout I have done in the calendar of training peaks

**Screenshots**
screenshot1 is the workout from Kinetic fit
![image](https://user-images.githubusercontent.com/45616004/79034051-b9041080-7be5-11ea-9fdc-83258c31b73d.png)
screenshot2 is the workout from TrainerRoad
![image](https://user-images.githubusercontent.com/45616004/79034071-c91bf000-7be5-11ea-8b9b-12af37766a30.png)

**Smartphone (please complete the following information):**
 - Device: oneplus 7
 - OS: Android 10
 - Kinetic Fit Version 2.5.4

**Trainer (please complete the following information):**
- Trainer: Road machine 2
- Firmware Version na

**Additional context**
na

**Comment by Lucylea** [comment]
I don't know if this issue is related to the third party TrainingPeaks

**Comment by lexicalninja** [comment]
This is releated to Training Peaks. When the activity is encoded, it is encoded with a TYPE and that is what is displaying. There is no option to set the name.
