### ISSUE TITLE
the missing cadence target data in "Sweet spot" workout

### ISSUE THREAD

**Issue by Lucylea** [kinetic-fit/fit-android-issues#28]
**Describe the bug**
in "Sweet Spot "workout, there is not a cadence target data

**To Reproduce**
1. Go to 'Sweet Spot'
2. Click on ' Warmup' and click on "skip"
3. the Workout begin
4. No cadence target is presented

**Expected behavior**
A workout should have both target power and cadence, I don;t know why this workout lacks of target cadence. I'm a beginner, I might understand wrong. 

**Screenshots**
![image](https://user-images.githubusercontent.com/45616004/79034335-bb676a00-7be7-11ea-8601-1f919acd1712.png)

**Smartphone (please complete the following information):**
 - Device: Oneplus 7
 - OS: Android 10
 - Kinetic Fit Version 2.5.4

**Trainer (please complete the following information):**
- Trainer: Road machine 2
- Firmware Version: na

**Additional context**
na

**Comment by lexicalninja** [comment]
There are no cadence targets for Sweet Spot. The workout is power zone focused and Kinetic did not include a cadence target when creating the workout. You can open a ticket with them through support and see if it was an oversight, but currently these are the targets in all versions of the app.
