### ISSUE TITLE
FTP Test not calculating new FTP

### ISSUE THREAD

**Issue by lexicalninja** [kinetic-fit/fit-android-issues#29]
**Describe the bug**
FTP workouts are not calculating the new FTP and are not asking user's to update their FTP on the Analysis Screen

**To Reproduce**

1. Complete one the the FTP Test workouts
2. Go to Analysis screen
3. New calculated FTP view should be shown at bottom of screen

**Expected behavior**
A view with the new calculated FTP and an option to update the user's FTP should show at the bottom of the analysis screen.

**Smartphone (please complete the following information):**
 - Device: ALL
 - OS: ALL
 - Kinetic Fit Version 2.4.5

**Comment by benomar34** [comment]
I've just done FTP test workout and that's the result:
![Screenshot_20200427-154713](https://user-images.githubusercontent.com/63738659/80382563-b589ae00-88a2-11ea-8530-38ee8cfd119b.png)
There's still a problem with the new calculated FTP but the option to update the user's FTP is shown.

**Comment by lexicalninja** [comment]
Maybe you just got really strong last week

**Comment by benomar34** [comment]
Yes! Really really strong!

Le lun. 27 avr. 2020 à 16:39, lexicalninja <notifications@github.com> a
écrit :

**Comment by lexicalninja** [comment]
Your new FTP can be set to 208

For some reason, the formula was multiplying the ftp calculation property by 100, instead of dividing by 100. so the number is 10,000 times bigger than it should be. I will fix this calculation, but this workout will always ask if you want to be superman. 

I will push this fix out this week. Thanks for reporting this. I appreciate your help a great deal

**Comment by benomar34** [comment]
Hi.
The formula is now correct with 2.5.10 (241)
I just had my correct FTP calculated.
When I click on "Set New FTP" my FTP is not updated. I had to change it myself (not a big issue...)
When I select "Free Ride" there's still "This workout will calculate a new FTP for you".
Thanks for the improvements.
