### ISSUE TITLE
Free trial of smart subscription was not in my data migration

### ISSUE THREAD

**Issue by benomar34** [kinetic-fit/fit-android-issues#31]
Describe the bug:
My Smart subscription free trial ends on May 04, 2020. I began the " Intro to Power Training 2" plan with app 1.4.23 but I can't test some workouts with beta app which are not in Core subscription as "4 x 4 min VO2max efforts with zone setup for the week".

To Reproduce:
    Go to 'Home page of beta app 2.5.5'
    Click on 'Ride' in the training plan
    Click on 'View Plan'
    Click on 'Calendar'
   Scroll down to a day with a workout not part of Core subscription as "4 x 4 min VO2max efforts with zone setup for the week".
    See error: the Duration is unreadable and if you click on the workout, it is a "Free Ride".

Expected behavior: I expected the subscription to be part of the data migration

Smartphone : 
    Device: Moto G5 (XT1676)
    OS: Android 8.1.0
    Kinetic Fit Version 2.5.5

Trainer : 
    Trainer: Kinetic Road Machine Smart 2
    Firmware Version 1.2

Additional context: Free Trial subscription on benomar34@gmail account

![Screenshot_20200415-193027](https://user-images.githubusercontent.com/63738659/79368623-fbb04a80-7f4f-11ea-827d-79cf00662bae.png)
![Screenshot_20200415-193039](https://user-images.githubusercontent.com/63738659/79368625-fce17780-7f4f-11ea-9263-f5d0ea7c4c7d.png)

.

**Comment by lexicalninja** [comment]
None of the subscription information was carried over from the other data base to this beta version. In beta, all versions use test subscriptions that are fake. There is no way to pull down that data from google for the beat testing. If you would like to test the subscription content for us, you may be able to "purchase" the sub again. It should say test card always passes and should not charge you for the subscription. 

Test subscriptions will give you a lot of email notifiactions because they try and test all of the phases of a subscription: initial sub, renewal, cancel. 

in the beta, you should be able to make test purchases, but the subs will have to be "repurchased" every few days because testing in google is done on accelerated timelines. 

again, this should not cost you money. 

If this does not work for you, you can go back to the production version or you can send me some screen shots of what you see when you try and get a sub in beta and we can work through this, but there really isn't a way in a beta test on google to get that other sub data

**Comment by benomar34** [comment]
Hi
Thank you for your quick reply.
I purchased a new subscription via Google Play and I'm in 7 days trial.
As a result now I have access to all training plans. But there are still
only 64 workouts available instead of approximately 200. And some of the
workouts included in the training plans are not among these 64.
I'm still unable to continue to test my training plan.
Any help?
Kind regards



Le mer. 15 avr. 2020 à 22:32, lexicalninja <notifications@github.com> a
écrit :

**Comment by lexicalninja** [comment]
Thats a different issue than I previously understood. I am reopening this to get it figured out. Thanks for the report.

**Comment by lexicalninja** [comment]
@benomar34 Please let me know if this is fixed with the release that was pushed yesterday when you have time. Thank you.

**Comment by benomar34** [comment]
With pleasure but I can't get the new beta app with Google Play.
Any other way to get it?

**Comment by lexicalninja** [comment]
You don't see the new version yet or you left the beta program?

sometimes you need to go into the myApps area and search for updates

**Comment by benomar34** [comment]
That's what I did but no I don't see the new version yet.
No didn't leave the beta program...

Le mer. 22 avr. 2020 à 19:21, lexicalninja <notifications@github.com> a
écrit :

**Comment by lexicalninja** [comment]
OK. you can try and see it by clearing the cache on the play store app. Otherwise it is still replicating down and you should get it today sometime

**Comment by benomar34** [comment]
No. I'm sorry but I've just tried what you said with no result...

**Comment by lexicalninja** [comment]
OK, it may just take some time, then.

**Comment by benomar34** [comment]
No other way to get the app?

**Comment by lexicalninja** [comment]
At this point, it has to do with google play getting it to you. There isnt anything I can do until they push it out and your phone picks up the update.

**Comment by benomar34** [comment]
Ok thanks. When it's ok I'll tell you if the bugs I've noticed are fixed

**Comment by lexicalninja** [comment]
Works for me. I am pretty sure they are fixed, so there is not really a rush. I just wanted to make sure I kept you in the loop when I pushed the changes

**Comment by benomar34** [comment]
2 hours ago the beta app 2.5.6 had been available on Google Play. I wanted to test issues #31 and #34 but as I've just reported in issue #35 I can't reach full sensors connection. I reverted to 2.5.5 and I reached full connection. 2.5.6 again with no improvement so I stay with 2.5.5..

**Comment by lexicalninja** [comment]
Thanks. I see what happened. There was a change to the way the app reads the bits and it was dropping the higher bits that say power is available. I am pushing a fix to that right now. Hopefully you get it sooner than the last update took.

**Comment by benomar34** [comment]
Hi I'm on Smart Monthly subscription with beta app 2.5.8 (239).
All the training plans are available:
![Screenshot_20200501-115342](https://user-images.githubusercontent.com/63738659/80797785-08b17880-8ba3-11ea-9257-291236e2bdea.png)
But not all the workouts (64 instead of approximately 200):
![Screenshot_20200501-115251](https://user-images.githubusercontent.com/63738659/80797851-2da5eb80-8ba3-11ea-9a28-4fc75c744999.png)
In some training plans when you select a workout which is not among these 64 you get "Free Ride" instead!
Anyway the "Free Ride" workout says that it will calculate a new FTP. Is that normal?
Kind Regards

**Comment by lexicalninja** [comment]
Nope. You should have a lot more workouts and the correct workout would change your ftp. I found the issue and am sending out a patch right now. Hopefully you see it today.

**Comment by benomar34** [comment]
Hi
It's now ok with 2.5.10 I've got access to all workouts.
Thanks
