### ISSUE TITLE
Difficulty calibrating

### ISSUE THREAD

**Issue by jacco411** [kinetic-fit/fit-android-issues#33]
**Describe the bug**
I have difficulty calibrating when the machine is warm.

**To Reproduce**
1. Go to any workout
2. Click on warmup. Then, after 9 minutes or so, click on calibrate.
3. The calibrate screen stays on the please wait screen and never allows the calibrate to start

**Expected behavior**
To start a calibration when warmed.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 9+
 - OS: Android 10
 - Kinetic Fit Version 2.5.5

**Trainer (please complete the following information):**
- Trainer: Rock n roll control
- Firmware Version 1.3

**Additional context**
I don't have any difficulty calibrating cold.

**Comment by lexicalninja** [comment]
are you using the iRide pod trainer or one of the SmartControl trainers?

**Comment by jacco411** [comment]
smart control trainer

**Comment by mcheppy** [comment]
I am experiencing the same issue several times now. when doing a ride in free ride mode after nine minutes I click the calibrate button. after speeding up and letting it soon down will not finish calibration and stays stuck on screen. after force closing the app, it can not find any of the sensors, and need to restart phone. after restarting, will calibrate without issue if I access calibration from sensor menu and not from free ride warmup button. 

I am using inride sensor.

**Comment by lexicalninja** [comment]
@mcheppy @jacco411 I found some bitwise errors in how the app was reading the sensor data that was causing issues for calibration. Please install version 2.5.8 (239) when you have a chance and see if the calibration errors are fixed. Thanks in advance

**Comment by mcheppy** [comment]
I am still having issues with calibration. I actually was not able to get a calibration to take at all yesterday.

**Comment by lexicalninja** [comment]
I am pushing a new version today for your sensor issue. I have tested Inride 2 and 3 and Smart Control 2 trainers and all three calibrate successfully in settings and in free ride warmup. 

Once you get the update, please let me know if your sensor is still acting up. We may need to get Kinetic hardware folks to help out for this.

**Comment by mcheppy** [comment]
did a ride today, tried to calibrate from free ride and wouldn't finish spin down. tried to restart app and phone but app could not find inride sensor but was able to find he monitor and cadence. after trying to calibrate also lost connection to watch. the only way get sensor to connect again was to reset the inride sensor by reverseing the battery. was then able to connect back to watch and app.

**Comment by jacco411** [comment]
I can confirm that this worked yesterday for me as expected. I will try again to be sure but it seems the problem has been resolved on my end. I did 9+ minutes on the warmup and then hit "calibrate." It subsequently allowed me to calibrate.

**Comment by jacco411** [comment]
I can confirm this worked for the second time in a row. I have not had a repeat of this problem since the last update.
