### ISSUE TITLE
Only Warmup and Lap 1 for the whole "Sub threshold 3x10" workout

### ISSUE THREAD

**Issue by benomar34** [kinetic-fit/fit-android-issues#34]
Describe the bug: On "Session Analysis" of the "Sub threshold 3x10" workout, there's only 1 lap for the whole workout after warmup.

To Reproduce:
    Go to 'All Workouts'
    Click on 'Sub threshold 3x10' then 'Warmup'
    Perform the workout
    See error at the end when you click on 'Results' or after when clicking on the list of your workouts:
    On Session Analysis there's only 1 lap for the whole workout after warmup.

Expected behavior: The workout should be divised in 7 laps after warmup.

Screenshots:
![Screenshot_20200417-101734](https://user-images.githubusercontent.com/63738659/79548832-58b61880-8096-11ea-9df9-cfe3fa3d28d0.png)

Smartphone :
Device: Moto G5 (XT1676)
OS: Android 8.1.0
Kinetic Fit Version 2.5.5

Trainer :
Trainer: Kinetic Road Machine Smart 2
Firmware Version 1.2

**Comment by lexicalninja** [comment]
Thanks. I think I see the issue. I will fix this here for next week.

**Comment by lexicalninja** [comment]
This should be fixed in Mondays update. It was not updating the stats at the top when you paged through the laps, either, so that should be fixed as well. I will circle back next week to see if this was fixed, but please let me know if this works.

**Comment by lexicalninja** [comment]
@benomar34 I pushed a new release yesterday that should fix this issue. Please let me know once you have a chance to do another workout. Thanks for reporting this.

**Comment by benomar34** [comment]
I confirm that it's now fine with 2.5.8. All laps are shown and the stats at the top are updated when I paged through the laps. Congratulations. Thank you.
