### ISSUE TITLE
Power not connected with app 2.5.6

### ISSUE THREAD

**Issue by benomar34** [kinetic-fit/fit-android-issues#35]
Describe the bug: with the new beta app 3.5.6 it's very difficult to connect the sensors and once it's done: there are only speed and cadence. The power is never connected.

To Reproduce:
Go to 'Sensors'
Click on the broken link to connect the sensors.
After several tries without any success, when it's connected: only speed and cadence are connected but not the power

Expected behavior: As with 3.5.5 at the first attempt speed, cadence and power were connected. And after connection, in the sensor settings it was possible to calibrate: screenshots with 3.5.5:
![Screenshot_20200424-151405](https://user-images.githubusercontent.com/63738659/80220957-e2d92080-8644-11ea-947a-7f84bf13e4c3.png)
![Screenshot_20200424-154116](https://user-images.githubusercontent.com/63738659/80221040-ff755880-8644-11ea-8591-fa23067c7c06.png)

Now with 3.5.6 in the sensor settings: power is not available and it's no longer possible to calibrate:
![Screenshot_20200424-151822](https://user-images.githubusercontent.com/63738659/80221132-27fd5280-8645-11ea-94d5-9acdfb391471.png)
![Screenshot_20200424-153806](https://user-images.githubusercontent.com/63738659/80221210-3f3c4000-8645-11ea-9f37-26871b2fedf5.png)

Smartphone :
Device: Moto G5 (XT1676)
OS: Android 8.1.0
Kinetic Fit Version 2.5.6

Trainer :
Trainer: Kinetic Road Machine Smart 2
Firmware Version 1.2

**Comment by lexicalninja** [comment]
Pushing a change to this now. Please let me know when you get 2.5.7 that this did indeed fix the issue.

Thanks

**Comment by benomar34** [comment]
I've just finished FTP test workout with 2.5.8: no longer any connection issue.
Thank you very much
