### ISSUE TITLE
Repeating Popup on fist app

### ISSUE THREAD

**Issue by yailkalaf** [kinetic-fit/fit-android-issues#36]
Hi, I'm working on:

Device Name: HUAWEY Y9 2019
Android Version: 9
RAM: 3.0GB
Internal Storage: 64GB
Security Patch: Oct 06, 2019
Kernel Version: 4.9.148

Just updated to kinetic fit v.2.5.8. 
On first start a pop up window started repeating the message:  "This app won't work without sensors. Would you like to enable them". Neiter clicking Ok or clicking the back button took the app out of the loop. Stopped the App and restarted it. 

No issues now. But diving into an infinite loop on first startup is not what I was expecting.

Regards

**Comment by lexicalninja** [comment]
Thanks. I will try and figure out why this was happening. the system was obviously not sending back the correct value when permissions are granted. Thanks for the report

**Comment by lexicalninja** [comment]
For users coming here, this should be fixed in 2.5.11 when it comes out. If you are on a version higher than this and still experience this, please comment and I will reopen the ticket
