### ISSUE TITLE
 Graph Metric frozes during workout

### ISSUE THREAD

**Issue by yailkalaf** [kinetic-fit/fit-android-issues#37]
Hi
**Describe the bug**
Halfway through my workout the metric graph froze and audio effects stopped working. On screen power target and output continued working so I finished the workout.
Session analysis picked up the workout correctly and I uploaded it to training peaks.

Note the negative interval time (-1:59:59) in the screenshot and the graph stopped 60% into the workout.
Note the HR unrealistic flat line after 1/3rd of the workout.

**To Reproduce**
Workout
At one time I had to pause/unpause the workout (sometime not sure how much) before the graph froze. 

**Expected behavior**
Continuous Graph and Audio cues.
Correct interval times.
Good HR metrics.

**Screenshots**
![Screenshot_20200428_192934_com kinetic fit](https://user-images.githubusercontent.com/64450095/80662931-98024300-8a60-11ea-8bb2-1dae1c00531b.jpg)
![Screenshot_20200428_192919_com kinetic fit](https://user-images.githubusercontent.com/64450095/80662936-9a649d00-8a60-11ea-9cd4-ac7bd892c86a.jpg)

**Smartphone (please complete the following information):**
Kinetic Fit: v2.5.8
Device Name: HUAWEY Y9 2019
Android Version: 9
RAM: 3.0GB
Internal Storage: 64GB
Security Patch: Oct 06, 2019
Kernel Version: 4.9.148

**Additional context**

Regards

**Comment by lexicalninja** [comment]
@yailkalaf 
I have tried replicating this and could not. Are you able to make this happen or was it the one time?

**Comment by yailkalaf** [comment]
Graph hasn't frozen again. Every Workout since has finished in a negative
time interval.

It would be nice if upon workout completion the App automatically takes you
to DE RESULT/Repeat Workout dialog.

I've stopped using the HRM.

**Comment by lexicalninja** [comment]
I am not sure I understand this: "It would be nice if upon workout completion the App automatically takes you
to DE RESULT/Repeat Workout dialog."

Can you please explain further for me?

**Comment by yailkalaf** [comment]
Sorry Typo.

When you finish a workout there is a button (lower right) to go to the
results page. From that page you can repeat the workout or leave.

I think it would be nice if upon workout completion the App automatically
takes you to the RESULTS page/dialog.

Hope this clarify my intention.

Regards
Yail





I am not sure I understand this: "It would be nice if upon workout

**Comment by lexicalninja** [comment]
Ah, yes. The reason it doesnt automatically go is because there was a large group of user's that did not like that happening. We had attempted this once and it did not get a great reception. 

I you would like, please open a new issue requesting this and I will try and make a setting option that just goes to the end.

This will be an enhancement request, so it will be further down the list in priority than bugs, but I can figure something out to let you skip that part if you would like.
