### ISSUE TITLE
Free Ride has FTP Calc Prop Banner

### ISSUE THREAD

**Issue by lexicalninja** [kinetic-fit/fit-android-issues#38]
When I select "Free Ride" there's still "This workout will calculate a new FTP for you".
Thanks for the improvements.

_Originally posted by @benomar34 in https://github.com/kinetic-fit/fit-android-issues/issues/29#issuecomment-623364732_

**Comment by lexicalninja** [comment]
FTP clac prop banner is showing in free ride, need to double check logic for displaying this

**Comment by benomar34** [comment]
Hi. It seems to be solved with 2.5.11.
Thanks
