### ISSUE TITLE
Upgrade doesn't preserve units preference

### ISSUE THREAD

**Issue by duanegran** [kinetic-fit/fit-android-issues#4]
**Describe the bug**
I've been using Fit App on iOS and have preferences set to metric.  After initial launch of the beta Fit App it shows units in imperial.  Other settings, such as my FTP appeared to have been preserved.

**Expected behavior**
Units should be preserved.

**Smartphone (please complete the following information):**
 - Device: Samsung 9
 - OS: Android
 - Version 9

**Comment by lexicalninja** [comment]
every time you open the new Fit the units change or just that initial migration loses the units?

**Comment by duanegran** [comment]
I believe it is just the initial unit preferences upon migration.  I will make a point of changing them and test if it is preserves it.  I expect it will.  Other settings seemed to come along fine I believe.

**Comment by lexicalninja** [comment]
I have added logic to keep this value and to save the value to the network profile instead of just on the phone so it should carry across all logins.
