### ISSUE TITLE
Cadence Sensor Not Connecting

### ISSUE THREAD

**Issue by yailkalaf** [kinetic-fit/fit-android-issues#40]
I own an inRide sensor and recently bought a cadence sensor.

**Describe the bug**
HARDWARE
Cadence Sensor came with a dead battery.
Changed the battery.
Cadence Sensor blinking both red and green until the battery died. 
Cadence Sensor visible to app for a brief moment then invisible.
Changed the battery BUT NOW sensor doesn't even blink nor is it visible.

SOFTWARE
When the cadence sensor was visible I could only pair it twice with the fit app but as soon as I started pedalling the cadence sensor would UNPAIR and the inRide cadence meter would activate.

**To Reproduce**
On sensors screen I paired inRide sensor and the cadence sensor. Don't remember which one first.
Disconnected cadence measuring from the inRide sensor.
Connected cadence measuring to the cadence sensor.
Started pedaling or a workout then the cadence sensor would disconnect (measuring) the the inRide measuring would activate (round icon).

**Expected behavior**
A working battery with the cadence sensor.
A working cadence sensor.
Measure/Report speed & power from the inRide sensor and the cadence from the cadence sensor.

**Smartphone (please complete the following information):**
Kinetic Fit: v2.5.8
Device Name: HUAWEY Y9 2019
Android Version: 9
RAM: 3.0GB
Internal Storage: 64GB
Security Patch: Oct 06, 2019
Kernel Version: 4.9.148

![Screenshot_20200507_174006_com kinetic fit](https://user-images.githubusercontent.com/64450095/82478783-6d276f80-9a9f-11ea-8bec-d06390d099cb.jpg)
![Screenshot_20200507_183658_com kinetic fit](https://user-images.githubusercontent.com/64450095/82478795-70226000-9a9f-11ea-9a47-9f972a0b4d51.jpg)
![Screenshot_20200507_190408_com kinetic fit](https://user-images.githubusercontent.com/64450095/82478805-73b5e700-9a9f-11ea-828f-074ea137a401.jpg)
![Screenshot_20200509_175953_com kinetic fit](https://user-images.githubusercontent.com/64450095/82478817-77496e00-9a9f-11ea-901e-ff2805a5ce70.jpg)

**Comment by lexicalninja** [comment]
Thank you @yailkalaf for bringing this over here for us. I have pushed an update today that should fix this. Please let me know when you receive version 2.5.12 (243) and have tested this. I have the same sensor here at my house and it was working here after my update. 

Thanks again for your help making the app better. We greatly appreciate it.

**Comment by yailkalaf** [comment]
Hi, did you push the update to the play store?

I am not seeing it

Regards

Y.

**Comment by lexicalninja** [comment]
I did. Updates to the play store can take anywhere from an hour to a day to show up on a user's device. Once its pushed, we are at the mercy of google and your phone as to how fast your play store app picks up the update.

**Comment by yailkalaf** [comment]
OK. Thanks.

**Comment by yailkalaf** [comment]
Happy to report that yesterday had my first workout with both the inRide
and Cadence sensors.

Thanks for the fast response

Regards
Y.
