### ISSUE TITLE
Can't calibrate

### ISSUE THREAD

**Issue by duanegran** [kinetic-fit/fit-android-issues#6]
**Describe the bug**
Tried to calibrate (R1) on the Fit App but it wouldn't work.  It is stuck on the display showing something along the lines of "preparing calibration, do not pedal".  I tried several things involving disconnecting, turning BT on/off, closing the app and still the same.  Even worse, when in this situation the "close" button isn't active and there is no clear way to get out of the screen other than to hit "disconnect" in the lower right.  Sometimes the display would show the current firmware version (2.40) and other times it wouldn't.  It would register speed and power so I'm reasonably sure it was communicating fine.  I fired up the Fit App on iOS after giving up and was able to calibrate straight away.  I've seen similar issues sometimes arise on the iOS version.  I'll keep trying now and again but today nothing would work I tried.

**Expected behavior**
1. The "do not pedal" part seems odd, I think we could remove unless someone is already riding at high speed
2. The firmware version was nice to show, but prior calibration figure is really what we want here
3. Basically, for calibration to work but that is kind of obvious here
4. Clear UI to abandon if there are issues.  I think the iOS version has a "skip" button or "reset" that works

**Smartphone (please complete the following information):**
 - Device: Samsung 9
 - OS: Android
 - Version: 9

**Trainer (please complete the following information):**
- Trainer: R1
- Firmware Version: 2.40

**Comment by duanegran** [comment]
I tried again to calibrate this morning and it was closer, but still no cigar.  I have some additional observations about the experience:

1. I connected to the R1 in the sensors section of the menu.  While pedaling it showed power, speed and cadence just fine.
2. I proceeded to do a free ride workout with the plan to calibrate at about 9 minutes into the ride, however the free ride reported zero watts.
3. I went back to sensors to look at the R1 and it showed -1 for the power and cadence (or was it speed, not sure) so I disconnected and re-paired.  Power showed up and I could go back to the workout and things worked as normal.  This is the second time I've seen this in two rides.
4. I rode for ~9 minutes fine and hit the calibrate button
5. It told me to spin up to 25 mph.  It registered fine and I did hit that target but it never said to coast.

So that is the problem report, but there are some usability issues here as well:

- In order to get to 25 mph I had to get over 600w of power.  I can do it, but damn that is a big ask.  On the iOS version by contrast I only need to hit around 265w.  I can't think of any reason why the two apps require very different top speed for calibration and I'm inclined to think the Android one is wrong.
- Since I couldn't calibrate, I was literally stuck.  There is no cancel operation and the Android back button (lower right) displays a pop up that it is disabled and that I should finish calibration.  I turned off BT and quit the app.  Not good.

**Comment by lexicalninja** [comment]
May be a soft device issue. Will take a look and see if there are ways to work around the issues.

I was able to calibrate the first try with the device and trainer in the testing room, so there is likely some device related issue or an issue with the samsung launcher that we need to work around. 

Please keep posting your experiences here as we work through this

**Comment by duanegran** [comment]
I did another test yesterday and was more patient to wait for everything to get connected and calibration did work.  This was using the C2 Control trainer.  The spin up felt normal.  I need to try again on the R1 to see if the resistance issue remains.  It may have been an artifact of all the services not being all ready.

So the short of it is that it works, but there are still some usability issues surrounding it.

**Comment by lexicalninja** [comment]
As long as it works, that is a good thing. We can make it more usable with some UI tricks that reduce confusion and aggravation. Let me know how it works out on the R1.

**Comment by smwinn7** [comment]
I have a road machine control unit and for whatever reason the calibration gets stuck in "pedal up to 25mph" mode I've had to force close the app and power the trainer and phone off/on in order to make sure there is not something going on. I try again and same thing or it gets stuck at "do not pedal"

Road machine control
Pixel 3
App version 1.43

**Comment by lexicalninja** [comment]
@smwinn7 thanks for coming to the forum. 

Unfortunately, this forum is for users using the beta version of the Android app and your current version is not that version. 

Please open a ticket with Customer Support at https://support.kurtkinetic.com/hc/en-us and we can try and answer your questions there

**Comment by lexicalninja** [comment]
@duanegran Added the overlay screen to the connection like we talked about. It will be in the next version to hit beta. If this doesn't solve the issue please reopen this.
