### ISSUE TITLE
Cannot Log On when on WiFi

### ISSUE THREAD

**Issue by SalomonSuspect** [kinetic-fit/fit-android-issues#7]
**Describe the bug**
The app crashes when I attempt to log on with wifi. 

**To Reproduce**
1. Open App
2. Enter username and password
3. Select "Log in"
4. App will Crash

**Expected behavior**
You should be able to log in

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - OS: Android
 - Version 9

**Trainer (please complete the following information):**
- Trainer: Road Machine Control
- Firmware Version

**Comment by lexicalninja** [comment]
I found the issue you are experiencing. There was an issue with the data coming out of the old database in an incorrect format. I am pushing a new build at the moment and you should be able to install the update in a few hours. You should see version 2.1.1 (218) in your side menu after a successful start up. 

I will leave this issue open until you respond with whether or not you can actually log in. 

Thank you for reporting the error and for helping to make Fit better.

**Comment by SalomonSuspect** [comment]
This issue has been resolved thank you for the quick response.
