### ISSUE TITLE
Issue with Stages PM as power source

### ISSUE THREAD

**Issue by duanegran** [kinetic-fit/fit-android-issues#9]
**Describe the bug**
I did a ride with the Stages left power meter as the power source and there are two issues I encountered:

1. The cadence doesn't register
2. The time stamp on the Fit File is about 628 hours too early.  See this in Analyzer:   https://analyze.dcrainmaker.com/#/dcc/c8d6ae02-7ffb-45cc-4da8-4d998f7a8696

I haven't had a chance to test with other PMs as the power source, but I will.  This is the second time I've seen this happen with the stages, so I'm sure it is reproducible.  I can try to compare against the iOS version of Kinetic Fit if that is helpful and report back.

**Comment by duanegran** [comment]
It appears that github doesn't accept .fit files as a valid extension, but attaching a zip containing the two files.
[stages-favero-fit-files.zip](https://github.com/kinetic-fit/fit-android-issues/files/4053936/stages-favero-fit-files.zip)

**Comment by duanegran** [comment]
Follow up on this issue.  I tested pairing the Stages PM with the app on iOS and it picked up cadence fine.  There was also no time offset issue, so I think both of these bugs are exclusive to the Android version.

**Comment by lexicalninja** [comment]
OK. this will get backlogged for a later date. It will likely need to be reviewed along with #11 when we get to that issue.

**Comment by lexicalninja** [comment]
I am having issues with my assioma pedal, hopefully all of these are related to these meters using the of Cycling Power Profile standard and not something else

**Comment by lexicalninja** [comment]
@duanegran please download 231 for android when you have a sec and check the stages meter. 

It should now show cadence. Please let me know if it doesn't.

I will be working on the fit file issue. It is tied to #17 so if this fixes the cadence issue, I will attach this to that issue and close this one. 

Thanks

**Comment by duanegran** [comment]
Will do!  Thanks for the update.  I should be able to test in the next couple of days.  The Android version should auto update, right?

**Comment by lexicalninja** [comment]
It should auto update. You just need to be on 231 or 232 for this. I pushed 232 with an internal change to try and fix some stuff that was crashing in other areas.

**Comment by lexicalninja** [comment]
@duanegran did this change fix the stages meter issue?
